name: Update-PKGBUILDs

on:
  create:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    name: update

    steps:
      - uses: actions/checkout@v2
      - run: ./dependencies.sh
      - run: ./builder.sh
      - run: sudo -u bash ./update.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
