name: Update-NTOU-Calendar

on:
  create:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - name: Install Archlinux
        run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh
      - run: ./update.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
