name: Update-PKGBUILDs

on:
  create:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    name: update

    steps:
      - run: pacman -Sy --needed --noconfirm git sudo jq
      - run: useradd builder && passwd -d builder && printf 'builder ALL=(ALL) ALL\n' | tee -a /etc/sudoers
      - run: sudo -u builder git clone https://github.com/${{ github.repository }}
      - run: sudo -u builder bash ./update.sh
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: stefanzweifel/git-auto-commit-action@v4
